In [1]:
import pandas as pd

In [2]:
dong_data= pd.read_csv("C:/Users/happytoseeyou/Desktop/nx_ny.csv", encoding="utf-8-sig")

In [3]:
dong_data.head()

,구분,admtn_dong_cd,1단계,2단계,3단계,nx,ny,경도(시),경도(분),경도(초),위도(시),위도(분),위도(초),경도(초/100),위도(초/100),위치업데이트
0,kor,1100000000,서울특별시,NaN,NaN,60,127,126,58,48.03,37,33,48.85,126.980008,37.563569,NaN
1,kor,1111000000,서울특별시,종로구,NaN,60,127,126,58,53.91,37,34,13.36,126.981642,37.570378,NaN
2,kor,1111051500,서울특별시,종로구,청운효자동,60,127,126,58,14.35,37,35,2.89,126.970652,37.584137,NaN
3,kor,1111053000,서울특별시,종로구,사직동,60,127,126,58,15.44,37,34,23.77,126.970956,37.573269,NaN
4,kor,1111054000,서울특별시,종로구,삼청동,60,127,126,59,2.32,37,34,56.73,126.983978,37.582425,NaN

In [4]:
dong_data = dong_data.fillna('0')

In [5]:
del dong_data['위치업데이트']
dong_data

,구분,admtn_dong_cd,1단계,2단계,3단계,nx,ny,경도(시),경도(분),경도(초),위도(시),위도(분),위도(초),경도(초/100),위도(초/100)
0,kor,1100000000,서울특별시,0,0,60,127,126,58,48.03,37,33,48.85,126.980008,37.563569
1,kor,1111000000,서울특별시,종로구,0,60,127,126,58,53.91,37,34,13.36,126.981642,37.570378
2,kor,1111051500,서울특별시,종로구,청운효자동,60,127,126,58,14.35,37,35,2.89,126.970652,37.584137
3,kor,1111053000,서울특별시,종로구,사직동,60,127,126,58,15.44,37,34,23.77,126.970956,37.573269
4,kor,1111054000,서울특별시,종로구,삼청동,60,127,126,59,2.32,37,34,56.73,126.983978,37.582425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3769,kor,5013060000,제주특별자치도,서귀포시,대천동,52,32,126,28,46.47,33,14,50.91,126.479575,33.247475
3770,kor,5013061000,제주특별자치도,서귀포시,중문동,51,32,126,26,12.40,33,14,53.44,126.436778,33.248178
3771,kor,5013062000,제주특별자치도,서귀포시,예래동,50,32,126,23,59.67,33,15,3.69,126.399908,33.251025
3772,kor,5019000000,이어도,0,0,28,8,0,0,0.00,0,0,0.00,0.000000,0.000000
3773,kor,5019099000,이어도,0,0,28,8,0,0,0.00,0,0,0.00,0.000000,0.000000

In [9]:
dong_data.value_counts()

구분   admtn_dong_cd  1단계    2단계     3단계   nx  ny   경도(시)  경도(분)  경도(초)  위도(시)  위도(분)  위도(초)  경도(초/100)   위도(초/100)
kor  1100000000     서울특별시  0       0     60  127  126    58     48.03  37     33     48.85  126.980008  37.563569    1
     4513067000     전라북도   군산시     구암동   56  92   126    44     46.03  35     58     57.88  126.746119  35.982744    1
     4513037000     전라북도   군산시     성산면   57  92   126    47     17.28  35     59     12.07  126.788133  35.986686    1
     4513038000     전라북도   군산시     나포면   58  93   126    50     6.96   36     1      28.44  126.835267  36.024567    1
     4513039000     전라북도   군산시     옥도면   43  95   125    58     44.59  36     6      59.69  125.979053  36.116581    1
                                                                                                                    ..
     4111100000     경기도    수원시장안구  0     60  121  127    0      44.00  37     18     3.64   127.012222  37.301011    1
     4111156000     경기도    수원시장안구  파장동   60  121  126    59     48.79  37     18     20.10  126.996886  37.305583    1
     4111156600     경기도    수원시장안구  율천동   60  121  126    58     24.88  37     17     41.17  126.973578  37.294769    1
     4111157100     경기도    수원시장안구  정자1동  60  121  126    59     36.15  37     17     57.79  126.993375  37.299386    1
     5019099000     이어도    0       0     28  8    0      0      0.00   0      0      0.00   0.000000    0.000000     1
Length: 3774, dtype: int64

In [7]:
dong_bucheon = dong_data[(dong_data['3단계']=='0')&(dong_data['1단계']=='경기도')&(dong_data['2단계']=='부천시')]

In [8]:
dong_bucheon = dong_bucheon[['admtn_dong_cd', '1단계', '2단계', 'nx', 'ny']].reset_index(drop=True)
dong_bucheon

   admtn_dong_cd  1단계  2단계  nx   ny
0     4119000000  경기도  부천시  56  125

In [10]:
df_56_125 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/bucheon/56_125_weather.csv", encoding="utf-8-sig")

In [12]:
final_data = pd.merge(left=df_56_125, right=dong_bucheon, how='left', on=['nx', 'ny'], sort=False)

In [13]:
final_data

,baseDate,baseTime,T1H,RN1,REH,PTY,WSD,nx,ny,admtn_dong_cd,1단계,2단계
0,20220101,900,-2.6,0.0,36.0,0.0,1.6,56,125,4119000000,경기도,부천시
1,20220101,1000,-1.4,0.0,32.0,0.0,1.5,56,125,4119000000,경기도,부천시
2,20220101,1100,0.5,0.0,28.0,0.0,1.6,56,125,4119000000,경기도,부천시
3,20220101,1200,1.8,0.0,28.0,0.0,1.2,56,125,4119000000,경기도,부천시
4,20220101,1300,2.8,0.0,29.0,0.0,1.4,56,125,4119000000,경기도,부천시
...,...,...,...,...,...,...,...,...,...,...,...,...
8011,20221201,400,-7.9,0.0,51.0,0.0,2.1,56,125,4119000000,경기도,부천시
8012,20221201,500,-8.0,0.0,47.0,0.0,0.9,56,125,4119000000,경기도,부천시
8013,20221201,600,-7.6,0.0,35.0,0.0,1.9,56,125,4119000000,경기도,부천시
8014,20221201,700,-6.8,0.0,32.0,0.0,0.7,56,125,4119000000,경기도,부천시
8015,20221201,800,-4.1,0.0,23.0,0.0,2.8,56,125,4119000000,경기도,부천시

In [18]:
final_data = final_data[['admtn_dong_cd', '1단계', '2단계','baseDate', 'baseTime', 'nx', 'ny', 'T1H', 'RN1', 'REH', 'PTY', 'WSD']]

In [19]:
final_data.to_csv("C:/Users/happytoseeyou/Desktop/bucheon_data_1206.csv",encoding="utf-8-sig", index=False)

In [20]:
final_data

,admtn_dong_cd,1단계,2단계,baseDate,baseTime,nx,ny,T1H,RN1,REH,PTY,WSD
0,4119000000,경기도,부천시,20220101,900,56,125,-2.6,0.0,36.0,0.0,1.6
1,4119000000,경기도,부천시,20220101,1000,56,125,-1.4,0.0,32.0,0.0,1.5
2,4119000000,경기도,부천시,20220101,1100,56,125,0.5,0.0,28.0,0.0,1.6
3,4119000000,경기도,부천시,20220101,1200,56,125,1.8,0.0,28.0,0.0,1.2
4,4119000000,경기도,부천시,20220101,1300,56,125,2.8,0.0,29.0,0.0,1.4
...,...,...,...,...,...,...,...,...,...,...,...,...
8011,4119000000,경기도,부천시,20221201,400,56,125,-7.9,0.0,51.0,0.0,2.1
8012,4119000000,경기도,부천시,20221201,500,56,125,-8.0,0.0,47.0,0.0,0.9
8013,4119000000,경기도,부천시,20221201,600,56,125,-7.6,0.0,35.0,0.0,1.9
8014,4119000000,경기도,부천시,20221201,700,56,125,-6.8,0.0,32.0,0.0,0.7
8015,4119000000,경기도,부천시,20221201,800,56,125,-4.1,0.0,23.0,0.0,2.8

,baseDate,baseTime,T1H,RN1,REH,PTY,WSD,nx,ny,admtn_dong_cd,1단계,2단계
0,20220101,900,-6.8,0.0,42.0,0.0,1.7,62,128,1126000000,서울특별시,중랑구
1,20220101,1000,-3.8,0.0,33.0,0.0,0.9,62,128,1126000000,서울특별시,중랑구
2,20220101,1100,-2.6,0.0,28.0,0.0,0.6,62,128,1126000000,서울특별시,중랑구
3,20220101,1200,-0.4,0.0,27.0,0.0,0.3,62,128,1126000000,서울특별시,중랑구
4,20220101,1300,0.0,0.0,28.0,0.0,0.8,62,128,1126000000,서울특별시,중랑구
...,...,...,...,...,...,...,...,...,...,...,...,...
182395,20221101,400,12.2,0.0,88.0,0.0,0.8,59,124,1154500000,서울특별시,금천구
182396,20221101,500,12.2,0.0,87.0,0.0,1.1,59,124,1154500000,서울특별시,금천구
182397,20221101,600,11.9,0.0,88.0,0.0,0.7,59,124,1154500000,서울특별시,금천구
182398,20221101,700,12.9,0.0,84.0,0.0,1.1,59,124,1154500000,서울특별시,금천구
182399,20221101,800,13.9,0.0,79.0,0.0,1.0,59,124,1154500000,서울특별시,금천구

In [52]:
seoul_nx_ny = mer

In [56]:
seoul_nx_ny.to_csv("C:/Users/happytoseeyou/Desktop/seoul_nx_ny.csv",encoding="utf-8-sig", index=False)

In [68]:
final_data = final_data[(final_data['T1H']!=-50)|(final_data['RN1']!=-1)]

In [69]:
final_data.to_csv("C:/Users/happytoseeyou/Desktop/seoul_data.csv",encoding="utf-8-sig", index=False)

In [71]:
case = final_data[(final_data['RN1']==-1)]

,admtn_dong_cd,1단계,2단계,baseDate,baseTime,nx,ny,T1H,RN1,REH,PTY,WSD
4130,1126000000,서울특별시,중랑구,20220622,200,62,128,-1.0,-1.0,-1.0,0.0,-1.0
6458,1126000000,서울특별시,중랑구,20220927,200,62,128,-1.0,-1.0,-1.0,-1.0,-1.0
14476,1111000000,서울특별시,종로구,20220530,1400,60,127,16.9,-1.0,58.0,-1.0,-1.0
14477,1114000000,서울특별시,중구,20220530,1400,60,127,16.9,-1.0,58.0,-1.0,-1.0
15556,1111000000,서울특별시,종로구,20220622,200,60,127,-1.0,-1.0,-1.0,0.0,-1.0
15557,1114000000,서울특별시,중구,20220622,200,60,127,-1.0,-1.0,-1.0,0.0,-1.0
20212,1111000000,서울특별시,종로구,20220927,200,60,127,-1.0,-1.0,-1.0,-1.0,-1.0
20213,1114000000,서울특별시,중구,20220927,200,60,127,-1.0,-1.0,-1.0,-1.0,-1.0
26018,1130500000,서울특별시,강북구,20220622,200,61,128,-1.0,-1.0,-1.0,0.0,-1.0
28346,1130500000,서울특별시,강북구,20220927,200,61,128,-1.0,-1.0,-1.0,-1.0,-1.0
37444,1132000000,서울특별시,도봉구,20220622,200,61,129,-1.0,-1.0,-1.0,0.0,-1.0
37445,1135000000,서울특별시,노원구,20220622,200,61,129,-1.0,-1.0,-1.0,0.0,-1.0
42100,1132000000,서울특별시,도봉구,20220927,200,61,129,-1.0,-1.0,-1.0,-1.0,-1.0
42101,1135000000,서울특별시,노원구,20220927,200,61,129,-1.0,-1.0,-1.0,-1.0,-1.0
56166,1120000000,서울특별시,성동구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
56167,1123000000,서울특별시,동대문구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
56168,1129000000,서울특별시,성북구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
63150,1120000000,서울특별시,성동구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
63151,1123000000,서울특별시,동대문구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
63152,1129000000,서울특별시,성북구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
69794,1117000000,서울특별시,용산구,20220622,200,60,126,-1.0,-1.0,-1.0,0.0,-1.0
72122,1117000000,서울특별시,용산구,20220927,200,60,126,-1.0,-1.0,-1.0,-1.0,-1.0
85350,1121500000,서울특별시,광진구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
85351,1171000000,서울특별시,송파구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
85352,1174000000,서울특별시,강동구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
92334,1121500000,서울특별시,광진구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
92335,1171000000,서울특별시,송파구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
92336,1174000000,서울특별시,강동구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
94485,1121500000,서울특별시,광진구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
94486,1171000000,서울특별시,송파구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
94487,1174000000,서울특별시,강동구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
107238,1147000000,서울특별시,양천구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
107239,1150000000,서울특별시,강서구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
107240,1156000000,서울특별시,영등포구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
114222,1147000000,서울특별시,양천구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
114223,1150000000,서울특별시,강서구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
114224,1156000000,서울특별시,영등포구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
127506,1138000000,서울특별시,은평구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
127507,1141000000,서울특별시,서대문구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
127508,1144000000,서울특별시,마포구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
129126,1138000000,서울특별시,은평구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
129127,1141000000,서울특별시,서대문구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
129128,1144000000,서울특별시,마포구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
136110,1138000000,서울특별시,은평구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
136111,1141000000,서울특별시,서대문구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
136112,1144000000,서울특별시,마포구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
146884,1159000000,서울특별시,동작구,20220622,200,59,125,-1.0,-1.0,-1.0,0.0,-1.0
146885,1162000000,서울특별시,관악구,20220622,200,59,125,-1.0,-1.0,-1.0,0.0,-1.0
151540,1159000000,서울특별시,동작구,20220927,200,59,125,-1.0,-1.0,-1.0,-1.0,-1.0
151541,1162000000,서울특별시,관악구,20220927,200,59,125,-1.0,-1.0,-1.0,-1.0,-1.0
157346,1165000000,서울특별시,서초구,20220622,200,61,125,-1.0,-1.0,-1.0,0.0,-1.0
159674,1165000000,서울특별시,서초구,20220927,200,61,125,-1.0,-1.0,-1.0,-1.0,-1.0
164642,1153000000,서울특별시,구로구,20220622,200,58,125,-1.0,-1.0,-1.0,0.0,-1.0
166970,1153000000,서울특별시,구로구,20220927,200,58,125,-1.0,-1.0,-1.0,-1.0,-1.0
171938,1168000000,서울특별시,강남구,20220622,200,61,126,-1.0,-1.0,-1.0,0.0,-1.0
174266,1168000000,서울특별시,강남구,20220927,200,61,126,-1.0,-1.0,-1.0,-1.0,-1.0
179234,1154500000,서울특별시,금천구,20220622,200,59,124,-1.0,-1.0,-1.0,0.0,-1.0
181562,1154500000,서울특별시,금천구,20220927,200,59,124,-1.0,-1.0,-1.0,-1.0,-1.0