In [1]:
import pandas as pd

In [2]:
dong_data= pd.read_csv("C:/Users/happytoseeyou/Desktop/nx_ny.csv", encoding="utf-8-sig")

In [3]:
dong_data.head()

,구분,admtn_dong_cd,1단계,2단계,3단계,nx,ny,경도(시),경도(분),경도(초),위도(시),위도(분),위도(초),경도(초/100),위도(초/100),위치업데이트
0,kor,1100000000,서울특별시,NaN,NaN,60,127,126,58,48.03,37,33,48.85,126.980008,37.563569,NaN
1,kor,1111000000,서울특별시,종로구,NaN,60,127,126,58,53.91,37,34,13.36,126.981642,37.570378,NaN
2,kor,1111051500,서울특별시,종로구,청운효자동,60,127,126,58,14.35,37,35,2.89,126.970652,37.584137,NaN
3,kor,1111053000,서울특별시,종로구,사직동,60,127,126,58,15.44,37,34,23.77,126.970956,37.573269,NaN
4,kor,1111054000,서울특별시,종로구,삼청동,60,127,126,59,2.32,37,34,56.73,126.983978,37.582425,NaN

In [4]:
dong_data = dong_data.fillna('0')

In [5]:
del dong_data['위치업데이트']
dong_data

,구분,admtn_dong_cd,1단계,2단계,3단계,nx,ny,경도(시),경도(분),경도(초),위도(시),위도(분),위도(초),경도(초/100),위도(초/100)
0,kor,1100000000,서울특별시,0,0,60,127,126,58,48.03,37,33,48.85,126.980008,37.563569
1,kor,1111000000,서울특별시,종로구,0,60,127,126,58,53.91,37,34,13.36,126.981642,37.570378
2,kor,1111051500,서울특별시,종로구,청운효자동,60,127,126,58,14.35,37,35,2.89,126.970652,37.584137
3,kor,1111053000,서울특별시,종로구,사직동,60,127,126,58,15.44,37,34,23.77,126.970956,37.573269
4,kor,1111054000,서울특별시,종로구,삼청동,60,127,126,59,2.32,37,34,56.73,126.983978,37.582425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3769,kor,5013060000,제주특별자치도,서귀포시,대천동,52,32,126,28,46.47,33,14,50.91,126.479575,33.247475
3770,kor,5013061000,제주특별자치도,서귀포시,중문동,51,32,126,26,12.40,33,14,53.44,126.436778,33.248178
3771,kor,5013062000,제주특별자치도,서귀포시,예래동,50,32,126,23,59.67,33,15,3.69,126.399908,33.251025
3772,kor,5019000000,이어도,0,0,28,8,0,0,0.00,0,0,0.00,0.000000,0.000000
3773,kor,5019099000,이어도,0,0,28,8,0,0,0.00,0,0,0.00,0.000000,0.000000

In [9]:
dong_busan = dong_data[(dong_data['3단계']=='0')&(dong_data['1단계']=='부산광역시')&(dong_data['2단계']!='0')]

In [25]:
dong_busan = dong_busan[['admtn_dong_cd', '1단계', '2단계', 'nx', 'ny']].reset_index(drop=True)
dong_busan

    admtn_dong_cd    1단계   2단계   nx  ny
0      2611000000  부산광역시    중구   97  74
1      2614000000  부산광역시    서구   97  74
2      2617000000  부산광역시    동구   98  75
3      2620000000  부산광역시   영도구   98  74
4      2623000000  부산광역시  부산진구   97  75
5      2626000000  부산광역시   동래구   98  76
6      2629000000  부산광역시    남구   98  75
7      2632000000  부산광역시    북구   96  76
8      2635000000  부산광역시  해운대구   99  75
9      2638000000  부산광역시   사하구   96  74
10     2641000000  부산광역시   금정구   98  77
11     2644000000  부산광역시   강서구   96  76
12     2647000000  부산광역시   연제구   98  76
13     2650000000  부산광역시   수영구   99  75
14     2653000000  부산광역시   사상구   96  75
15     2671000000  부산광역시   기장군  100  77

In [26]:
df_96_74 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/96_74_weather.csv", encoding="utf-8-sig")
df_96_75 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/96_75_weather.csv", encoding="utf-8-sig")
df_96_76 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/96_76_weather.csv", encoding="utf-8-sig")
df_97_74 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/97_74_weather.csv", encoding="utf-8-sig")
df_97_75 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/97_75_weather.csv", encoding="utf-8-sig")
df_98_74 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/98_74_weather.csv", encoding="utf-8-sig")
df_98_75 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/98_75_weather.csv", encoding="utf-8-sig")
df_98_76 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/98_76_weather.csv", encoding="utf-8-sig")
df_98_77 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/98_77_weather.csv", encoding="utf-8-sig")
df_99_75 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/99_75_weather.csv", encoding="utf-8-sig")
df_100_77 = pd.read_csv("C:/Users/happytoseeyou/Desktop/weather/busan/100_77_weather.csv", encoding="utf-8-sig")

In [27]:
mer=pd.concat([df_96_74, df_96_75, df_96_76, df_97_74, df_97_75, df_98_74, df_98_75, df_98_76, df_98_77, df_99_75, 
              df_100_77], axis=0)
mer

      baseDate  baseTime  T1H  RN1   REH  PTY  WSD   nx  ny
0     20220101       900 -1.3  0.0  22.0  0.0  0.8   96  74
1     20220101      1000  1.3  0.0  18.0  0.0  0.3   96  74
2     20220101      1100  4.2  0.0  14.0  0.0  0.1   96  74
3     20220101      1200  3.6  0.0  14.0  0.0  0.3   96  74
4     20220101      1300  5.5  0.0   8.0  0.0  0.1   96  74
...        ...       ...  ...  ...   ...  ...  ...  ...  ..
8011  20221201       400 -0.2  0.0  27.0  0.0  1.1  100  77
8012  20221201       500 -0.5  0.0  30.0  0.0  1.7  100  77
8013  20221201       600 -0.6  0.0  29.0  0.0  1.8  100  77
8014  20221201       700 -0.1  0.0  28.0  0.0  0.4  100  77
8015  20221201       800  1.7  0.0  26.0  0.0  0.8  100  77

[88176 rows x 9 columns]

In [28]:
mer

      baseDate  baseTime  T1H  RN1   REH  PTY  WSD   nx  ny
0     20220101       900 -1.3  0.0  22.0  0.0  0.8   96  74
1     20220101      1000  1.3  0.0  18.0  0.0  0.3   96  74
2     20220101      1100  4.2  0.0  14.0  0.0  0.1   96  74
3     20220101      1200  3.6  0.0  14.0  0.0  0.3   96  74
4     20220101      1300  5.5  0.0   8.0  0.0  0.1   96  74
...        ...       ...  ...  ...   ...  ...  ...  ...  ..
8011  20221201       400 -0.2  0.0  27.0  0.0  1.1  100  77
8012  20221201       500 -0.5  0.0  30.0  0.0  1.7  100  77
8013  20221201       600 -0.6  0.0  29.0  0.0  1.8  100  77
8014  20221201       700 -0.1  0.0  28.0  0.0  0.4  100  77
8015  20221201       800  1.7  0.0  26.0  0.0  0.8  100  77

[88176 rows x 9 columns]

In [29]:
final_data = pd.merge(left=mer, right=dong_busan, how='left', on=['nx', 'ny'], sort=False)

In [30]:
final_data

,baseDate,baseTime,T1H,RN1,REH,PTY,WSD,nx,ny,admtn_dong_cd,1단계,2단계
0,20220101,900,-1.3,0.0,22.0,0.0,0.8,96,74,2638000000,부산광역시,사하구
1,20220101,1000,1.3,0.0,18.0,0.0,0.3,96,74,2638000000,부산광역시,사하구
2,20220101,1100,4.2,0.0,14.0,0.0,0.1,96,74,2638000000,부산광역시,사하구
3,20220101,1200,3.6,0.0,14.0,0.0,0.3,96,74,2638000000,부산광역시,사하구
4,20220101,1300,5.5,0.0,8.0,0.0,0.1,96,74,2638000000,부산광역시,사하구
...,...,...,...,...,...,...,...,...,...,...,...,...
128251,20221201,400,-0.2,0.0,27.0,0.0,1.1,100,77,2671000000,부산광역시,기장군
128252,20221201,500,-0.5,0.0,30.0,0.0,1.7,100,77,2671000000,부산광역시,기장군
128253,20221201,600,-0.6,0.0,29.0,0.0,1.8,100,77,2671000000,부산광역시,기장군
128254,20221201,700,-0.1,0.0,28.0,0.0,0.4,100,77,2671000000,부산광역시,기장군
128255,20221201,800,1.7,0.0,26.0,0.0,0.8,100,77,2671000000,부산광역시,기장군

In [31]:
final_data = final_data[['admtn_dong_cd', '1단계', '2단계','baseDate', 'baseTime', 'nx', 'ny', 'T1H', 'RN1', 'REH', 'PTY', 'WSD']]

In [32]:
final_data

,admtn_dong_cd,1단계,2단계,baseDate,baseTime,nx,ny,T1H,RN1,REH,PTY,WSD
0,2638000000,부산광역시,사하구,20220101,900,96,74,-1.3,0.0,22.0,0.0,0.8
1,2638000000,부산광역시,사하구,20220101,1000,96,74,1.3,0.0,18.0,0.0,0.3
2,2638000000,부산광역시,사하구,20220101,1100,96,74,4.2,0.0,14.0,0.0,0.1
3,2638000000,부산광역시,사하구,20220101,1200,96,74,3.6,0.0,14.0,0.0,0.3
4,2638000000,부산광역시,사하구,20220101,1300,96,74,5.5,0.0,8.0,0.0,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...
128251,2671000000,부산광역시,기장군,20221201,400,100,77,-0.2,0.0,27.0,0.0,1.1
128252,2671000000,부산광역시,기장군,20221201,500,100,77,-0.5,0.0,30.0,0.0,1.7
128253,2671000000,부산광역시,기장군,20221201,600,100,77,-0.6,0.0,29.0,0.0,1.8
128254,2671000000,부산광역시,기장군,20221201,700,100,77,-0.1,0.0,28.0,0.0,0.4
128255,2671000000,부산광역시,기장군,20221201,800,100,77,1.7,0.0,26.0,0.0,0.8

In [34]:
final_data.to_csv("C:/Users/happytoseeyou/Desktop/busan_data_1206.csv",encoding="utf-8-sig", index=False)

In [52]:
seoul_nx_ny = mer

In [56]:
seoul_nx_ny.to_csv("C:/Users/happytoseeyou/Desktop/seoul_nx_ny.csv",encoding="utf-8-sig", index=False)

In [68]:
final_data = final_data[(final_data['T1H']!=-50)|(final_data['RN1']!=-1)]

In [69]:
final_data.to_csv("C:/Users/happytoseeyou/Desktop/seoul_data.csv",encoding="utf-8-sig", index=False)

In [71]:
case = final_data[(final_data['RN1']==-1)]

,admtn_dong_cd,1단계,2단계,baseDate,baseTime,nx,ny,T1H,RN1,REH,PTY,WSD
4130,1126000000,서울특별시,중랑구,20220622,200,62,128,-1.0,-1.0,-1.0,0.0,-1.0
6458,1126000000,서울특별시,중랑구,20220927,200,62,128,-1.0,-1.0,-1.0,-1.0,-1.0
14476,1111000000,서울특별시,종로구,20220530,1400,60,127,16.9,-1.0,58.0,-1.0,-1.0
14477,1114000000,서울특별시,중구,20220530,1400,60,127,16.9,-1.0,58.0,-1.0,-1.0
15556,1111000000,서울특별시,종로구,20220622,200,60,127,-1.0,-1.0,-1.0,0.0,-1.0
15557,1114000000,서울특별시,중구,20220622,200,60,127,-1.0,-1.0,-1.0,0.0,-1.0
20212,1111000000,서울특별시,종로구,20220927,200,60,127,-1.0,-1.0,-1.0,-1.0,-1.0
20213,1114000000,서울특별시,중구,20220927,200,60,127,-1.0,-1.0,-1.0,-1.0,-1.0
26018,1130500000,서울특별시,강북구,20220622,200,61,128,-1.0,-1.0,-1.0,0.0,-1.0
28346,1130500000,서울특별시,강북구,20220927,200,61,128,-1.0,-1.0,-1.0,-1.0,-1.0
37444,1132000000,서울특별시,도봉구,20220622,200,61,129,-1.0,-1.0,-1.0,0.0,-1.0
37445,1135000000,서울특별시,노원구,20220622,200,61,129,-1.0,-1.0,-1.0,0.0,-1.0
42100,1132000000,서울특별시,도봉구,20220927,200,61,129,-1.0,-1.0,-1.0,-1.0,-1.0
42101,1135000000,서울특별시,노원구,20220927,200,61,129,-1.0,-1.0,-1.0,-1.0,-1.0
56166,1120000000,서울특별시,성동구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
56167,1123000000,서울특별시,동대문구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
56168,1129000000,서울특별시,성북구,20220622,200,61,127,-1.0,-1.0,-1.0,0.0,-1.0
63150,1120000000,서울특별시,성동구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
63151,1123000000,서울특별시,동대문구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
63152,1129000000,서울특별시,성북구,20220927,200,61,127,-1.0,-1.0,-1.0,-1.0,-1.0
69794,1117000000,서울특별시,용산구,20220622,200,60,126,-1.0,-1.0,-1.0,0.0,-1.0
72122,1117000000,서울특별시,용산구,20220927,200,60,126,-1.0,-1.0,-1.0,-1.0,-1.0
85350,1121500000,서울특별시,광진구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
85351,1171000000,서울특별시,송파구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
85352,1174000000,서울특별시,강동구,20220622,200,62,126,-1.0,-1.0,-1.0,0.0,-1.0
92334,1121500000,서울특별시,광진구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
92335,1171000000,서울특별시,송파구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
92336,1174000000,서울특별시,강동구,20220927,200,62,126,-1.0,-1.0,-1.0,-1.0,-1.0
94485,1121500000,서울특별시,광진구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
94486,1171000000,서울특별시,송파구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
94487,1174000000,서울특별시,강동구,20221026,2300,62,126,10.3,-1.0,71.0,-1.0,-1.0
107238,1147000000,서울특별시,양천구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
107239,1150000000,서울특별시,강서구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
107240,1156000000,서울특별시,영등포구,20220622,200,58,126,-1.0,-1.0,-1.0,0.0,-1.0
114222,1147000000,서울특별시,양천구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
114223,1150000000,서울특별시,강서구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
114224,1156000000,서울특별시,영등포구,20220927,200,58,126,-1.0,-1.0,-1.0,-1.0,-1.0
127506,1138000000,서울특별시,은평구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
127507,1141000000,서울특별시,서대문구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
127508,1144000000,서울특별시,마포구,20220530,1400,59,127,16.9,-1.0,58.0,-1.0,-1.0
129126,1138000000,서울특별시,은평구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
129127,1141000000,서울특별시,서대문구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
129128,1144000000,서울특별시,마포구,20220622,200,59,127,-1.0,-1.0,-1.0,0.0,-1.0
136110,1138000000,서울특별시,은평구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
136111,1141000000,서울특별시,서대문구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
136112,1144000000,서울특별시,마포구,20220927,200,59,127,-1.0,-1.0,-1.0,-1.0,-1.0
146884,1159000000,서울특별시,동작구,20220622,200,59,125,-1.0,-1.0,-1.0,0.0,-1.0
146885,1162000000,서울특별시,관악구,20220622,200,59,125,-1.0,-1.0,-1.0,0.0,-1.0
151540,1159000000,서울특별시,동작구,20220927,200,59,125,-1.0,-1.0,-1.0,-1.0,-1.0
151541,1162000000,서울특별시,관악구,20220927,200,59,125,-1.0,-1.0,-1.0,-1.0,-1.0
157346,1165000000,서울특별시,서초구,20220622,200,61,125,-1.0,-1.0,-1.0,0.0,-1.0
159674,1165000000,서울특별시,서초구,20220927,200,61,125,-1.0,-1.0,-1.0,-1.0,-1.0
164642,1153000000,서울특별시,구로구,20220622,200,58,125,-1.0,-1.0,-1.0,0.0,-1.0
166970,1153000000,서울특별시,구로구,20220927,200,58,125,-1.0,-1.0,-1.0,-1.0,-1.0
171938,1168000000,서울특별시,강남구,20220622,200,61,126,-1.0,-1.0,-1.0,0.0,-1.0
174266,1168000000,서울특별시,강남구,20220927,200,61,126,-1.0,-1.0,-1.0,-1.0,-1.0
179234,1154500000,서울특별시,금천구,20220622,200,59,124,-1.0,-1.0,-1.0,0.0,-1.0
181562,1154500000,서울특별시,금천구,20220927,200,59,124,-1.0,-1.0,-1.0,-1.0,-1.0